// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgV3KhHby2mfIwdix1Tc6B282dMp2o7DE',
    appId: '1:428499376844:web:7c61ae8ca1a18aa15dc069',
    messagingSenderId: '428499376844',
    projectId: 'dinos-81943',
    authDomain: 'dinos-81943.firebaseapp.com',
    storageBucket: 'dinos-81943.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GT_nc5bo88mncEUnTUHT8uDVW_2uHa4',
    appId: '1:428499376844:android:7de32d1a9432cec25dc069',
    messagingSenderId: '428499376844',
    projectId: 'dinos-81943',
    storageBucket: 'dinos-81943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7SkEy1jX3-Ji7k888ua6Oc-Z2_oZmJ9s',
    appId: '1:428499376844:ios:1fc1458b9ccf76bf5dc069',
    messagingSenderId: '428499376844',
    projectId: 'dinos-81943',
    storageBucket: 'dinos-81943.firebasestorage.app',
    iosBundleId: 'com.example.dinoApp',
  );
}
